// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgdkRKwClC2HLFNagGz3vIC5M8zwHFoKQ',
    appId: '1:634048616620:web:39b18905d9b9bdea182709',
    messagingSenderId: '634048616620',
    projectId: 't-store-594c3',
    authDomain: 't-store-594c3.firebaseapp.com',
    storageBucket: 't-store-594c3.firebasestorage.app',
    measurementId: 'G-GNY3PZR5JP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvet0ULAA3Auubs26Qz9YrdV9zImUaGDo',
    appId: '1:634048616620:android:775c8ebacae698d0182709',
    messagingSenderId: '634048616620',
    projectId: 't-store-594c3',
    storageBucket: 't-store-594c3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZulnAfVKSKtGJwhI44kls2RJ5dFSj6QA',
    appId: '1:634048616620:ios:a897a6f548eedba5182709',
    messagingSenderId: '634048616620',
    projectId: 't-store-594c3',
    storageBucket: 't-store-594c3.firebasestorage.app',
    iosBundleId: 'com.example.tStore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLKIMiWq0nGahpQFNWcNi6OY3TokY9rg8',
    appId: '1:602486709132:ios:09a37d75638a0baf9714a9',
    messagingSenderId: '602486709132',
    projectId: 'imagesignup-a2764',
    databaseURL: 'https://imagesignup-a2764-default-rtdb.firebaseio.com',
    storageBucket: 'imagesignup-a2764.appspot.com',
    androidClientId: '602486709132-mk1o6dgv9ej3p37ld6u9e8e3iv8jr4qe.apps.googleusercontent.com',
    iosClientId: '602486709132-60a7fegedpaqdh5uj2ut0h00kc8g15ag.apps.googleusercontent.com',
    iosBundleId: 'com.example.tStore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAgdkRKwClC2HLFNagGz3vIC5M8zwHFoKQ',
    appId: '1:634048616620:web:e08ea31bd6a9bee6182709',
    messagingSenderId: '634048616620',
    projectId: 't-store-594c3',
    authDomain: 't-store-594c3.firebaseapp.com',
    storageBucket: 't-store-594c3.firebasestorage.app',
    measurementId: 'G-BNSDMT084Z',
  );

}